### ISSUE TITLE
Integrate Docker

### ISSUE THREAD

**Issue by lawrenceslng** [GayaHealth/Gaya_Website#5]
We need to integrate Docker and have everything live in a container for easier deployment

**Comment by shenghungKuan** [comment]
I'll do some research on it, and try to finish it

**Comment by lawrenceslng** [comment]
I found 2 tutorials on integrating docker with a React/Node project:
https://dev.to/numtostr/running-react-and-node-js-in-one-shot-with-docker-3o09
https://medium.com/bb-tutorials-and-thoughts/dockerizing-react-app-with-nodejs-backend-26352561b0b7

Regarding which image to use, I think we can use the defacto image `node:<version>` and the specific version we want to use will be 18.16.1 as that's the latest recommended from node itself:
https://nodejs.org/en

See if these are helpful

**Comment by shenghungKuan** [comment]
- https://www.stereolabs.com/docs/docker/creating-your-image/
- https://docs.docker.com/samples/react/

The Dockerfile code reference:

`FROM node:18.16.0-alpine3.17
RUN mkdir -p /opt/app  
WORKDIR /opt/app  
COPY src/package.json src/package-lock.json  
RUN npm install  
COPY src/ .  
EXPOSE 3000  
CMD [ "npm", "start"]`

Backend:

//syntax=docker/dockerfile:1.4  
FROM node:lts-buster-slim AS development

//Create app directory
WORKDIR /usr/src/app

COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm ci

COPY . /usr/src/app

EXPOSE 3000
CMD [ "npm", "run", "dev" ]
FROM development as dev-envs
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends git
EOF

RUN <<EOF
useradd -s /bin/bash -m vscode
groupadd docker
usermod -aG docker vscode
EOF

//install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /
CMD [ "npm", "run", "dev" ]

Frontend:

// syntax=docker/dockerfile:1.4

//Create image based on the official Node image from dockerhub
FROM node:lts-buster AS development

// Create app directory
WORKDIR /usr/src/app

// Copy dependency definitions
COPY package.json /usr/src/app
COPY package-lock.json /usr/src/app

// Install dependecies
// RUN npm set progress=false \
//    && npm config set depth 0 \
//    && npm i install
RUN npm ci

// Get all the code needed to run the app
COPY . /usr/src/app

// Expose the port the app runs in
EXPOSE 3000

// Serve the app
CMD ["npm", "start"]

FROM development as dev-envs
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends git
EOF

RUN <<EOF
useradd -s /bin/bash -m vscode
groupadd docker
usermod -aG docker vscode
EOF
// install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /
CMD [ "npm", "start" ]

**Comment by lawrenceslng** [comment]
I don't think we need to create our own image like in the first link, but I think you can try to use the examples from the docker docs and the code above (with some modifications) and see if you can get it working

**Comment by shenghungKuan** [comment]
This includes node images
[https://hub.docker.com/_/node](url)

This includes some description and introduction
[https://github.com/nodejs/docker-node/tree/d9c01570c0f72a40cbaece69c378d7c8187c56e9](url)

For combining the two docker files, we may need a "docker-compose.yml" file to achieve that
