### ISSUE TITLE
Delete current React app default page

### ISSUE THREAD

**Issue by zhunan123** [GayaHealth/Gaya_Website#6]
Currently we have a default React page when we run the application, which is showed below
<img width="1664" alt="react_default_page" src="https://github.com/GayaHealth/Gaya_Website/assets/47227727/9d434858-ea2f-45c4-b98b-6629993b81af">

Need to take out default react page.

**Comment by lawrenceslng** [comment]
Should we have different js files for each part of the front page like here:
https://react.dev/learn/importing-and-exporting-components

So for example, we can have a header file, a 1st component, 2nd component etc file, then a footer file?

**Comment by zhunan123** [comment]
> Should we have different js files for each part of the front page like here: https://react.dev/learn/importing-and-exporting-components
> 
> So for example, we can have a header file, a 1st component, 2nd component etc file, then a footer file?

yeah, we should have different files for each component, maybe in src folder we can create a components folder, and put head.js, footer.js and other components inside the components folder.
