### ISSUE TITLE
Implement Join Waitlist Button

### ISSUE THREAD

**Issue by zhunan123** [GayaHealth/Gaya_Website#7]
Need to implement join the waitlist button once we click join waitlist button on the home landing page. And the component display is showed below. 
<img width="702" alt="Screenshot 2023-06-26 at 5 54 29 PM" src="https://github.com/GayaHealth/Gaya_Website/assets/47227727/52b0d0b7-de23-4fbc-9a1d-23175a717ca2">

**Comment by lawrenceslng** [comment]
Using a modal for future reference: https://mui.com/material-ui/react-modal/#basic-modal

**Comment by lawrenceslng** [comment]
Most likely integrating with Beehiiv:  https://www.youtube.com/watch?v=4Wk-lpHYNSo

**Comment by lawrenceslng** [comment]
Note: No API call with unpaid plan, can only use iframe
https://developers.beehiiv.com/docs/v2/bktd9a7mxo67n-create-an-api-key
