### ISSUE TITLE
README Overview Section

### ISSUE THREAD

**Issue by lawrenceslng** [GayaHealth/Gaya_Website#8]
The overview should contain some background info on Gaya as a brand and what this website/app does (features and functionalities). We can split this up into subsections if we want as well like follows:

### Gaya

- What is Gaya
- What our website/app does

can put some info about the vision, mission statement, and slogan in this section as well

### Technologies Used

- Give some background on how we decided on the technologies used to create this app
- What the technologies do 

What else do you guys think?

**Comment by shenghungKuan** [comment]
The structure of the project e.g. docker files, package.json, client, server, components, etc.

Is the sample usage kinda similar to the build process?
Should we keep it?

No idea what to put in the testing process
